const imagesData = [
  {
    id: 1,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584481/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxMjMxNjM1My9vcmlnaW5hbF8yY2IwZmE4OWQ0NjQ2NjUyODNlMjVlNDk2ZDg1ZTc2ZC5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_efuv3t.webp",
    title: "Case Study 1",
    description: "This is a detailed description of Case Study 3.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-3",
    type: "image",
  },
  {
    id: 2,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584481/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI3ODA5NTM5L29yaWdpbmFsXzU1OTc3YmIxZGUxYzQxMWQyM2ZlOTgwODkwOWU4ZjZiLnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_gzp4fv.webp",
    title: "Case Study 2",
    description: "This is a detailed description of Case Study 2.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-2",
    type: "image",
  },
  {
    id: 3,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584481/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI1NTU2ODY4L29yaWdpbmFsXzEyYjQ4NDM2N2FiZmM1Y2YzMjc4NDJkOGI0ZWJiMWE2LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_juxktq.webp",
    title: "Case Study 3",
    description: "This is a detailed description of Case Study 3.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-3",
    type: "image",
  },
  {
    id: 4,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI5NTAzNDI4L29yaWdpbmFsX2JmYjRmYWMyMjI4NDdkZWYzOTk2MjE2OWJjNDk3YTExLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_kp7uky.webp",
    title: "Case Study 4",
    description: "This is a detailed description of Case Study 4.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-4",
    type: "image",
  },
  {
    id: 5,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI4MDMzNzY5L29yaWdpbmFsXzRjZGRlNGU5YjdiODFmOWRjMDMwYzg1MmY5N2E0MmVkLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_up5lff.webp",
    title: "Case Study 5",
    description: "This is a detailed description of Case Study 5.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-5",
    type: "image",
  },
  {
    id: 6,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxNTI2MDQyNi9vcmlnaW5hbF81ZDE0Y2U1MDBkMWNhMGI2MzgwNzRiZTc2YmRkZjcwMi5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_a3qha7.webp",
    title: "Case Study 6",
    description: "This is a detailed description of Case Study 6.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-6",
    type: "image",
  },
  {
    id: 7,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxNTI2MDQyOC9vcmlnaW5hbF8xNWYzZDJhZGI0YmU2Njc0OGExNWI5MGQ2YWY5NmE2Ni5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_dv18ov.webp",
    title: "Case Study 7",
    description: "This is a detailed description of Case Study 7.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-7",
    type: "image",
  },
  {
    id: 8,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxNzE0MzEwMi9vcmlnaW5hbF8wNWUzMzI1N2Q4OWQ0MzlhMDZlZjM0ZDdiNzIwY2E3NC5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_hyvgux.webp",
    title: "Case Study 8",
    description: "This is a detailed description of Case Study 8.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-8",
    type: "image",
  },
  {
    id: 9,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxNzQ3NTE4MC9vcmlnaW5hbF8xM2U5ZjM4YmZhMDRmMDcwNzc2MWEwZWVjNWQxNjcwZC5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_htekna.webp",
    title: "Case Study 9",
    description: "This is a detailed description of Case Study 9.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-9",
    type: "image",
  },
  {
    id: 10,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxMzUzMjM4L29yaWdpbmFsXzRhZGM3YTVhZGRkN2FkMzIyMGFhYzliN2FlZWE0NzczIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo2MDAsImhlaWdodCI6NjAwLCJmaXQiOiJpbnNpZGUiLCJ3aXRob3V0RW5sYXJnZW1lbnQiOn_nkri41.webp",
    title: "Case Study 10",
    description: "This is a detailed description of Case Study 10.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-10",
    type: "image",
  },
  {
    id: 11,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxMTM5MjkxNC9vcmlnaW5hbF82MjA1NjQwZjdkNGEzZjNjY2Q1ZjU2YTI5MDIzOTMwYS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_opv0l3.webp",
    title: "Case Study 11",
    description: "This is a detailed description of Case Study 11.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-11",
    type: "image",
  },
  {
    id: 12,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584482/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiI4OTU4MTkyL29yaWdpbmFsX2Y3YWY2MDRlOTYyNmQ1ZGUwZWIzNDMwMzZmODdkZjBhLnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_c3dpl0.webp",
    title: "Case Study 12",
    description: "This is a detailed description of Case Study 12.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-12",
    type: "image",
  },
  {
    id: 13,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584483/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIyOTg4MTMzL29yaWdpbmFsXzA0ZDNkZmJjZDZkYzk2MjVhMTFjODFhNDFjZDcwYjRkLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_xpv0bt.webp",
    title: "Case Study 13",
    description: "This is a detailed description of Case Study 13.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-13",
    type: "image",
  },
  {
    id: 14,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584483/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIyMDIxNjY0L29yaWdpbmFsX2ExZjQ5YjljN2Q2YzQ0YTNmYjk3OWQ2MTc1OGIyOThmLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_uhvwdm.webp",
    title: "Case Study 14",
    description: "This is a detailed description of Case Study 14.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-14",
    type: "image",
  },
  {
    id: 15,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584483/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIxMTk0NTE5NC9vcmlnaW5hbF85ZjZiMDE4Y2IyMDlmNGE2OGZjYmRiMWJiMzNhZDE2Yi5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiaGVpZ2h0Ijo2MDAsImZpdCI6Imluc2lkZSIsIndpdGhvdXRFbmxhcmdlbW_b6g4nx.webp",
    title: "Case Study 15",
    description: "This is a detailed description of Case Study 15.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-15",
    type: "image",
  },
  {
    id: 16,
    url: "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732584483/eyJidWNrZXQiOiJhcmVuYV9pbWFnZXMiLCJrZXkiOiIzNzAyNTc4L29yaWdpbmFsXzRhZjJiZWNmOTMzNWYxMGVjZWUwYTE2YjYxMDQ4MjVmLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW_rn2ie7.webp",
    title: "Case Study 16",
    description: "This is a detailed description of Case Study 16.",
    year: 2022,
    technologies: "JavaScript, GSAP",
    link: "https://example.com/case-study-16",
    type: "image",
  },
  {
    id: 17,
    url: "https://res.cloudinary.com/dtps5ugbf/video/upload/v1751070732/a570bca3-90ac-f473-4927-b94ff290a9e4-ezgif.com-crop-video_hr93xs.mp4",
    poster:
      "https://res.cloudinary.com/dtps5ugbf/image/upload/v1732588424/pexels-kelly-2949824_hnsopl.jpg",
    title: "Generative Art",
    description:
      "A generative art piece that uses p5.js to create a dynamic and interactive visual experience.",
    year: 2023,
    technologies: "P5, Video, JavaScript",
    type: "video",
  },
];

const images = imagesData.map((media) => {
  if (media.type === "video" && media.url.includes("cloudinary")) {
    const posterUrl = media.url.replace(/\.mp4$/, ".jpg");
    return { ...media, poster: posterUrl };
  }
  return media;
});

export default images;
